repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.4"
    hooks:
      - id: ruff
        pass_filenames: true
        entry: bash -c 'ruff check --fix --show-fixes --output-format=${RUFF_OUTPUT_FORMAT:-full} "$@"'
      - id: ruff-format
  - repo: local
    hooks:
      - id: ruff-warning
        name: Ruff Migration Warning
        entry: |
          bash -c 'echo -e "\n\033[1;33m[WARNING]\033[0m\n\nWe are immigrating to \033[1mruff\033[0m as the linter and formatter and \033[1mpre-commit\033[0m as the managing tool.\nSee: https://github.com/volcengine/verl/pull/1010\n\nIf your branch is based on a previous commit, simply merging might trigger overwhelming linting errors,\nwhile \033[1myou are only expected to resolve ones in the files related to your PR\033[0m.\n\nPlease try:\n\n1. \033[1mgit rebase main\033[0m\n2. or manually copy the files you changed to a new branch\n\nto \033[1monly commit the files you really changed\033[0m for the CI to lint."'
        language: system
        always_run: true
        verbose: true
